@startuml Logger_Module_Details
!theme materia
skinparam linetype ortho
skinparam BackgroundColor White

title Nível 4: Detalhes do Módulo Logger

package "logger.py" {
  component "Funções de Logging" {
    () get_logger
  }
  note right of "Funções de Logging"
    Configura logging para:
    - Console (INFO e acima)
    - Arquivo 'src/softscrape/outputs/errors/log_errors.txt' (ERROR e acima)
  end note
}
@enduml